// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOCixr92pMVY5Ko87T9CdK_qAzzsIeP28',
    appId: '1:531834802972:web:6ac488dd921e5021eda0d9',
    messagingSenderId: '531834802972',
    projectId: 'joblinker-ba4a9',
    authDomain: 'joblinker-ba4a9.firebaseapp.com',
    storageBucket: 'joblinker-ba4a9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDv3gcEZOQQIAMw3crkk0bUig_NA07w0DI',
    appId: '1:531834802972:android:b63ddc74f01df9c8eda0d9',
    messagingSenderId: '531834802972',
    projectId: 'joblinker-ba4a9',
    storageBucket: 'joblinker-ba4a9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCG9lb3XCJGhkq8QxGlfs7h6UxFpgzN0m4',
    appId: '1:531834802972:ios:f480cff42f62eeefeda0d9',
    messagingSenderId: '531834802972',
    projectId: 'joblinker-ba4a9',
    storageBucket: 'joblinker-ba4a9.appspot.com',
    iosBundleId: 'com.example.joblinker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCG9lb3XCJGhkq8QxGlfs7h6UxFpgzN0m4',
    appId: '1:531834802972:ios:f480cff42f62eeefeda0d9',
    messagingSenderId: '531834802972',
    projectId: 'joblinker-ba4a9',
    storageBucket: 'joblinker-ba4a9.appspot.com',
    iosBundleId: 'com.example.joblinker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCOCixr92pMVY5Ko87T9CdK_qAzzsIeP28',
    appId: '1:531834802972:web:d7cbfb5771f72a72eda0d9',
    messagingSenderId: '531834802972',
    projectId: 'joblinker-ba4a9',
    authDomain: 'joblinker-ba4a9.firebaseapp.com',
    storageBucket: 'joblinker-ba4a9.appspot.com',
  );
}
